[build]
command = """
composer install \
&& ./vendor/bin/drush tome:install -y \
&& LUNR_DRUSH=./vendor/bin/drush node web/modules/contrib/lunr/js/index.node.js default \
&& ./vendor/bin/drush simple-sitemap-generate -y -l https://open-source-literature.org \
&& ./vendor/bin/drush tome:static -l https://open-source-literature.org
"""

publish = "html"

[build.environment]
PHP_VERSION="7.4"
